import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker, {route} from './worker.mjs';
const origin='https://metasaif.github.io';
function setup(){
 const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./migrations/0001_inquiries.sql',import.meta.url),'utf8'));
 const DB={prepare(sql){let params=[];return {bind(...values){params=values;return this;},async first(){return db.prepare(sql).get(...params)||null;},async all(){return {results:db.prepare(sql).all(...params)};},async run(){const result=db.prepare(sql).run(...params);return {meta:{changes:Number(result.changes)}};}};}};
 return {db,env:{DB,INQUIRY_LIMITER:{limit:async()=>({success:true})},ADMIN_LIMITER:{limit:async()=>({success:true})},ADMIN_TOKEN:'test-only-access-key-with-at-least-32-characters',TURNSTILE_SECRET_KEY:'test-only-secret',ALLOWED_ORIGIN:origin,TURNSTILE_HOSTNAME:'metasaif.github.io'}};
}
const payload=()=>({name:'Test Person',email:'test@example.org',message:'Please help build an appointment scheduling product.',budget:'Not sure yet',consent:true,website:'',turnstileToken:'test-token',requestId:crypto.randomUUID()});
function request(path,method='GET',data,auth,from=origin){const headers={Origin:from};if(data!==undefined)headers['Content-Type']='application/json';if(auth)headers.Authorization='Bearer '+auth;return new Request('https://worker.example'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)});}
const verified=async()=>Response.json({success:true,hostname:'metasaif.github.io',action:'inquiry'});
test('unconfigured backend fails closed and health requires migrated DB',async()=>{const response=await worker.fetch(request('/api/health'),{ALLOWED_ORIGIN:origin});assert.equal(response.status,503);const {env}=setup();assert.equal((await route(request('/api/health'),env)).data.ready,true);});
test('rejects foreign origins and only permits exact CORS origin',async()=>{const {env}=setup();assert.equal((await worker.fetch(request('/api/inquiries','POST',payload(),null,'https://evil.example'),env)).status,403);const preflight=await worker.fetch(request('/api/inquiries','OPTIONS'),env);assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);});
test('persists inquiry and retries produce exactly one row',async()=>{const {db,env}=setup();const data=payload();let calls=0;const fetcher=async()=>{calls++;return verified();};const a=await route(request('/api/inquiries','POST',data),env,fetcher);const b=await route(request('/api/inquiries','POST',data),env,fetcher);assert.equal(a.data.reference,b.data.reference);assert.equal(calls,1);assert.equal(db.prepare('SELECT count(*) AS n FROM inquiries').get().n,1);assert.equal(db.prepare('SELECT status FROM inquiries').get().status,'new');});
test('reusing request ID with changed content is rejected',async()=>{const {env}=setup();const data=payload();await route(request('/api/inquiries','POST',data),env,verified);await assert.rejects(route(request('/api/inquiries','POST',{...data,name:'Different Name'}),env,verified),e=>e.status===409);});
test('validation, consent and honeypot block writes',async()=>{for(const change of [{email:'bad'},{message:'short'},{consent:false},{website:'spam'},{name:'x'},{message:'x'.repeat(4001)}]){const {db,env}=setup();await assert.rejects(route(request('/api/inquiries','POST',{...payload(),...change}),env,verified),e=>e.status===400);assert.equal(db.prepare('SELECT count(*) AS n FROM inquiries').get().n,0);}});
test('Turnstile success, hostname and action are all required',async()=>{for(const result of [{success:false},{success:true,hostname:'evil.example',action:'inquiry'},{success:true,hostname:'metasaif.github.io',action:'other'}]){const {db,env}=setup();await assert.rejects(route(request('/api/inquiries','POST',payload()),env,async()=>Response.json(result)),e=>e.status===400);assert.equal(db.prepare('SELECT count(*) AS n FROM inquiries').get().n,0);}});
test('verification outage cannot save a record',async()=>{const {env}=setup();await assert.rejects(route(request('/api/inquiries','POST',payload()),env,async()=>{throw Error('offline');}),e=>e.status===503);});
test('submission and admin rate limits are enforced',async()=>{const {env}=setup();env.INQUIRY_LIMITER.limit=async()=>({success:false});assert.equal((await worker.fetch(request('/api/inquiries','POST',payload()),env)).status,429);env.ADMIN_LIMITER.limit=async()=>({success:false});assert.equal((await worker.fetch(request('/api/admin/inquiries'),env)).status,429);});
test('admin authorization protects reads, status updates and deletion',async()=>{const {env}=setup();for(const method of ['GET','PATCH','DELETE']){const url=method==='GET'?'/api/admin/inquiries':'/api/admin/inquiries/'+crypto.randomUUID();assert.equal((await worker.fetch(request(url,method,method==='PATCH'?{status:'completed'}:undefined,'wrong'),env)).status,401);}});
test('admin filters, changes status, replies data and deletes',async()=>{const {env}=setup();const saved=await route(request('/api/inquiries','POST',payload()),env,verified);const id=saved.data.reference;const admin=(url,method='GET',data)=>request(url,method,data,env.ADMIN_TOKEN);assert.equal((await route(admin('/api/admin/inquiries?status=new'),env)).data.inquiries.length,1);await route(admin('/api/admin/inquiries/'+id,'PATCH',{status:'contacted'}),env);assert.equal((await route(admin('/api/admin/inquiries?status=new'),env)).data.inquiries.length,0);assert.equal((await route(admin('/api/admin/inquiries?status=contacted'),env)).data.inquiries.length,1);await assert.rejects(route(admin('/api/admin/inquiries/'+id,'PATCH',{status:'bogus'}),env),e=>e.status===400);await route(admin('/api/admin/inquiries/'+id,'DELETE'),env);assert.equal((await route(admin('/api/admin/inquiries'),env)).data.inquiries.length,0);});
test('pagination covers 27 records exactly once in reverse date order',async()=>{const {db,env}=setup();for(let i=0;i<27;i++){const saved=await route(request('/api/inquiries','POST',payload()),env,verified);db.prepare('UPDATE inquiries SET created_at=? WHERE id=?').run(new Date(1700000000000+i*1000).toISOString(),saved.data.reference);}const a=(await route(request('/api/admin/inquiries','GET',undefined,env.ADMIN_TOKEN),env)).data;const b=(await route(request('/api/admin/inquiries?after='+a.next,'GET',undefined,env.ADMIN_TOKEN),env)).data;assert.equal(a.inquiries.length,25);assert.equal(b.inquiries.length,2);assert.equal(b.next,null);const all=[...a.inquiries,...b.inquiries];assert.equal(new Set(all.map(x=>x.id)).size,27);assert.deepEqual(all.map(x=>x.created_at),all.map(x=>x.created_at).sort().reverse());});
test('SQL-like and markup content stays literal and database remains intact',async()=>{const {db,env}=setup();const data={...payload(),name:"Robert'); DROP TABLE inquiries;--",message:'<script>alert("test")</script> This is a literal message.'};await route(request('/api/inquiries','POST',data),env,verified);assert.equal(db.prepare('SELECT name FROM inquiries').get().name,data.name);});
test('oversized requests are rejected and responses never cache private data',async()=>{const {env}=setup();const response=await worker.fetch(request('/api/inquiries','POST',{...payload(),message:'x'.repeat(13000)}),env);assert.equal(response.status,413);assert.equal(response.headers.get('Cache-Control'),'no-store');});

test('Pages migration permits both exact origins and binds verification to the requesting hostname',async()=>{const {env}=setup();const pages='https://mohammadsaifkhan.pages.dev';env.ALLOWED_ORIGIN=origin+','+pages;env.TURNSTILE_HOSTNAME='metasaif.github.io,mohammadsaifkhan.pages.dev';for(const from of [origin,pages]){const response=await worker.fetch(request('/api/health','GET',undefined,null,from),env);assert.equal(response.status,200);assert.equal(response.headers.get('Access-Control-Allow-Origin'),from);}assert.equal((await worker.fetch(request('/api/health','GET',undefined,null,pages+'.evil.example'),env)).status,403);const req=()=>request('/api/inquiries','POST',payload(),null,pages);await assert.rejects(route(req(),env,verified),e=>e.status===400);assert.equal((await route(req(),env,async()=>Response.json({success:true,hostname:'mohammadsaifkhan.pages.dev',action:'inquiry'}))).data.saved,true);});
